# Schema for the configuration files of the inlinemanual module.

inlinemanual.settings:
  type: mapping
  label: 'InlineManual settings'
  mapping:
    site_key:
      type: string
      label: 'Site API Key'
    widget:
      type: mapping
      label: 'Widget'
      mapping:
        title:
          type: string
          label: 'Widget title'
        color:
          type: string
          label: 'Widget color'
        text_color:
          type: string
          label: 'Widget text color'
